# Generated by Django 2.2 on 2024-06-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userIncome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={},
        ),
    ]
