# Generated by Django 2.2 on 2024-06-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userIncome', '0004_auto_20240602_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ['-date']},
        ),
    ]
